library(dplyr)

#setwd("D:/Coursera/R_WorkingDir")
dt <- read.table("household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
subset_dt <- filter(dt, dt$Date %in% c("1/2/2007","2/2/2007"))
subset_dt$Date <- as.POSIXlt(as.character(subset_dt$Date), format="%d/%m/%Y")
subset_dt <- mutate(subset_dt, TimeStamp=as.POSIXct(paste(Date, Time)))

png(file = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
par(mar = c(4,4,2,2))
with(subset_dt2, plot(subset_dt2$TimeStamp, subset_dt$Global_active_power, main = "", type="l", ylab = "Global Active Power", xlab=""))
with(subset_dt2, plot(subset_dt2$TimeStamp, subset_dt$Voltage, main = "", type="l", ylab = "Voltage", xlab="datetime"))
with(subset_dt2, plot(subset_dt2$TimeStamp, subset_dt$Sub_metering_1, main = "", type="n", ylab = "Energy sub metering", xlab="", col="black"))
with(subset_dt2, points(subset_dt2$TimeStamp, subset_dt$Sub_metering_1, col = "black", type = "l"))
with(subset_dt2, points(subset_dt2$TimeStamp, subset_dt$Sub_metering_2, col = "red", type = "l"))
with(subset_dt2, points(subset_dt2$TimeStamp, subset_dt$Sub_metering_3, col = "blue", type = "l"))
legend("topright", pch = "-", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), lwd=3)
with(subset_dt2, plot(subset_dt2$TimeStamp, subset_dt$Global_reactive_power, main = "", type="l", ylab = "Global Reactive Power", xlab="datetime"))
dev.off()